'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
      return queryInterface.bulkInsert('Reviews', [{ userId: `1`, spotId: `1`, content: `very goood, I like`},
      { userId: `1`, spotId: `17`, content: `nom nom nom`},
      { userId: `1`, spotId: `20`, content: `I got in trouble here`},
      { userId: `1`, spotId: `22`, content: `check out this sweet score I got!`},
      { userId: `23`, spotId: `4`, content: `warning, this place isn't as safe as it used to be`},
      { userId: `22`, spotId: `36`, content: `it was too crowded here`},
      { userId: `6`, spotId: `28`, content: `I found a bottle of Cheval Blanc 1947 here`},
      { userId: `14`, spotId: `9`, content: `I didn't find anything good`},
      { userId: `18`, spotId: `14`, content: `This dumpster was moved???`},
      { userId: `2`, spotId: `8`, content: `This place is kind of sketchy`},
      { userId: `9`, spotId: `2`, content: `I made a friend here`},
      { userId: `13`, spotId: `18`, content: `Look, I found some expensive cheese!`},
      { userId: `5`, spotId: `10`, content: `the meat was still good`},
      { userId: `9`, spotId: `20`, content: `Whoever was here last didn't clean up after themselves >:(`},
      { userId: `3`, spotId: `17`, content: `very goood, I like`},
      { userId: `7`, spotId: `7`, content: `nom nom nom`},
      { userId: `2`, spotId: `19`, content: `I got in trouble here`},
      { userId: `21`, spotId: `16`, content: `check out this sweet score I got!`},
      { userId: `8`, spotId: `17`, content: `warning, this place isn't as safe as it used to be`},
      { userId: `13`, spotId: `31`, content: `it was too crowded here`},
      { userId: `13`, spotId: `4`, content: `I found a bottle of Cheval Blanc 1947 here`},
      { userId: `14`, spotId: `9`, content: `I didn't find anything good`},
      { userId: `10`, spotId: `32`, content: `This dumpster was moved???`},
      { userId: `6`, spotId: `33`, content: `This place is kind of sketchy`},
      { userId: `4`, spotId: `31`, content: `I made a friend here`},
      { userId: `11`, spotId: `36`, content: `Look, I found some expensive cheese!`},
      { userId: `3`, spotId: `12`, content: `the meat was still good`},
      { userId: `7`, spotId: `28`, content: `Whoever was here last didn't clean up after themselves >:(`},
      { userId: `15`, spotId: `18`, content: `very goood, I like`},
      { userId: `15`, spotId: `2`, content: `nom nom nom`},
      { userId: `2`, spotId: `22`, content: `I got in trouble here`},
      { userId: `15`, spotId: `30`, content: `check out this sweet score I got!`},
      { userId: `16`, spotId: `9`, content: `warning, this place isn't as safe as it used to be`},
      { userId: `21`, spotId: `31`, content: `it was too crowded here`},
      { userId: `21`, spotId: `33`, content: `I found a bottle of Cheval Blanc 1947 here`},
      { userId: `23`, spotId: `19`, content: `I didn't find anything good`},
      { userId: `10`, spotId: `36`, content: `This dumpster was moved???`},
      { userId: `7`, spotId: `13`, content: `This place is kind of sketchy`},
      { userId: `6`, spotId: `12`, content: `I made a friend here`},
      { userId: `2`, spotId: `19`, content: `Look, I found some expensive cheese!`},
      { userId: `1`, spotId: `22`, content: `the meat was still good`},
      { userId: `11`, spotId: `35`, content: `Whoever was here last didn't clean up after themselves >:(`},
      { userId: `1`, spotId: `17`, content: `very goood, I like`},
      { userId: `1`, spotId: `30`, content: `nom nom nom`},
      { userId: `1`, spotId: `19`, content: `I got in trouble here`},
      { userId: `1`, spotId: `34`, content: `check out this sweet score I got!`},
      { userId: `10`, spotId: `31`, content: `warning, this place isn't as safe as it used to be`},
      { userId: `11`, spotId: `2`, content: `it was too crowded here`},
      { userId: `2`, spotId: `25`, content: `I found a bottle of Cheval Blanc 1947 here`},
      { userId: `7`, spotId: `33`, content: `I didn't find anything good`},
      { userId: `19`, spotId: `14`, content: `This dumpster was moved???`},
      { userId: `1`, spotId: `27`, content: `This place is kind of sketchy`},
      { userId: `3`, spotId: `17`, content: `I made a friend here`},
      { userId: `1`, spotId: `2`, content: `very goood, I like`},
      { userId: `1`, spotId: `21`, content: `nom nom nom`},
      { userId: `1`, spotId: `33`, content: `I got in trouble here`},
      { userId: `1`, spotId: `21`, content: `check out this sweet score I got!`},
      { userId: `14`, spotId: `35`, content: `warning, this place isn't as safe as it used to be`},
      { userId: `19`, spotId: `26`, content: `it was too crowded here`},
      { userId: `5`, spotId: `3`, content: `I found a bottle of Cheval Blanc 1947 here`},
      { userId: `13`, spotId: `17`, content: `I didn't find anything good`},
      { userId: `19`, spotId: `13`, content: `This dumpster was moved???`},
      { userId: `16`, spotId: `26`, content: `This place is kind of sketchy`},
      { userId: `11`, spotId: `35`, content: `I made a friend here`},
      { userId: `21`, spotId: `21`, content: `Look, I found some expensive cheese!`},
      { userId: `8`, spotId: `14`, content: `the meat was still good`},
      { userId: `13`, spotId: `18`, content: `Whoever was here last didn't clean up after themselves >:(`},
      { userId: `8`, spotId: `7`, content: `very goood, I like`},
      { userId: `13`, spotId: `29`, content: `nom nom nom`},
      { userId: `21`, spotId: `3`, content: `I got in trouble here`},
      { userId: `16`, spotId: `7`, content: `check out this sweet score I got!`},
      { userId: `15`, spotId: `28`, content: `warning, this place isn't as safe as it used to be`},
      { userId: `8`, spotId: `10`, content: `it was too crowded here`},
      { userId: `16`, spotId: `20`, content: `I found a bottle of Cheval Blanc 1947 here`},
      { userId: `17`, spotId: `1`, content: `I didn't find anything good`},
      { userId: `2`, spotId: `24`, content: `This dumpster was moved???`},
      { userId: `6`, spotId: `23`, content: `This place is kind of sketchy`}      
      ], {});
  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.bulkDelete('People', null, {});
    */
  }
};
